

  {
    id: 524366433,
    node_id: 'R_kgDOH0EyYQ',
    name: 'avs_landing',
    full_name: 'etherealHero/avs_landing',
    private: false,
    owner: {
      login: 'etherealHero',
      id: 97192799,
      node_id: 'U_kgDOBcsLXw',
      avatar_url: 'https://avatars.githubusercontent.com/u/97192799?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/etherealHero',
      html_url: 'https://github.com/etherealHero',
      followers_url: 'https://api.github.com/users/etherealHero/followers',
      following_url: 'https://api.github.com/users/etherealHero/following{/other_user}',
      gists_url: 'https://api.github.com/users/etherealHero/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/etherealHero/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/etherealHero/subscriptions',
      organizations_url: 'https://api.github.com/users/etherealHero/orgs',
      repos_url: 'https://api.github.com/users/etherealHero/repos',
      events_url: 'https://api.github.com/users/etherealHero/events{/privacy}',
      received_events_url: 'https://api.github.com/users/etherealHero/received_events',
      type: 'User',
      site_admin: false
    },
    html_url: 'https://github.com/etherealHero/avs_landing',
    description: 'Адаптивная верстка LandingPage Строительная компания',
    fork: false,
    url: 'https://api.github.com/repos/etherealHero/avs_landing',
    forks_url: 'https://api.github.com/repos/etherealHero/avs_landing/forks',
    keys_url: 'https://api.github.com/repos/etherealHero/avs_landing/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/etherealHero/avs_landing/collaborators{/co
llaborator}',
    teams_url: 'https://api.github.com/repos/etherealHero/avs_landing/teams',
    hooks_url: 'https://api.github.com/repos/etherealHero/avs_landing/hooks',
    issue_events_url: 'https://api.github.com/repos/etherealHero/avs_landing/issues/events{/num
ber}',
    events_url: 'https://api.github.com/repos/etherealHero/avs_landing/events',
    assignees_url: 'https://api.github.com/repos/etherealHero/avs_landing/assignees{/user}',
    branches_url: 'https://api.github.com/repos/etherealHero/avs_landing/branches{/branch}',
    tags_url: 'https://api.github.com/repos/etherealHero/avs_landing/tags',
    blobs_url: 'https://api.github.com/repos/etherealHero/avs_landing/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/etherealHero/avs_landing/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/etherealHero/avs_landing/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/etherealHero/avs_landing/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/etherealHero/avs_landing/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/etherealHero/avs_landing/languages',
    stargazers_url: 'https://api.github.com/repos/etherealHero/avs_landing/stargazers',
    contributors_url: 'https://api.github.com/repos/etherealHero/avs_landing/contributors',
    subscribers_url: 'https://api.github.com/repos/etherealHero/avs_landing/subscribers',
    subscription_url: 'https://api.github.com/repos/etherealHero/avs_landing/subscription',
    commits_url: 'https://api.github.com/repos/etherealHero/avs_landing/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/etherealHero/avs_landing/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/etherealHero/avs_landing/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/etherealHero/avs_landing/issues/comments{/
number}',
    contents_url: 'https://api.github.com/repos/etherealHero/avs_landing/contents/{+path}',
    compare_url: 'https://api.github.com/repos/etherealHero/avs_landing/compare/{base}...{head}
',
    merges_url: 'https://api.github.com/repos/etherealHero/avs_landing/merges',
    archive_url: 'https://api.github.com/repos/etherealHero/avs_landing/{archive_format}{/ref}'
,
    downloads_url: 'https://api.github.com/repos/etherealHero/avs_landing/downloads',
    issues_url: 'https://api.github.com/repos/etherealHero/avs_landing/issues{/number}',
    pulls_url: 'https://api.github.com/repos/etherealHero/avs_landing/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/etherealHero/avs_landing/milestones{/number}'
,
    notifications_url: 'https://api.github.com/repos/etherealHero/avs_landing/notifications{?si
nce,all,participating}',
    labels_url: 'https://api.github.com/repos/etherealHero/avs_landing/labels{/name}',
    releases_url: 'https://api.github.com/repos/etherealHero/avs_landing/releases{/id}',
    deployments_url: 'https://api.github.com/repos/etherealHero/avs_landing/deployments',
    created_at: '2022-08-13T10:27:23Z',
    updated_at: '2022-08-13T10:55:33Z',
    pushed_at: '2022-08-13T10:56:35Z',
    git_url: 'git://github.com/etherealHero/avs_landing.git',
    ssh_url: 'git@github.com:etherealHero/avs_landing.git',
    clone_url: 'https://github.com/etherealHero/avs_landing.git',
    svn_url: 'https://github.com/etherealHero/avs_landing',
    homepage: 'https://etherealhero.github.io/avs_landing/',
    size: 2907,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'HTML',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 0,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 0,
    license: null,
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [],
    visibility: 'public',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'main',
    permissions: {
      admin: true,
      maintain: true,
      push: true,
      triage: true,
      pull: true
    },
    score: 1
  },
